--CREATE DATABASE OnlineStore

CREATE TABLE Orders(
OrderID INT PRIMARY KEY NOT NULL,
CustomerID INT
)

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY NOT NULL,
Name VARCHAR(50),
BirthDate DATE,
CityID INT
)

CREATE TABLE Cities(
CityID INT PRIMARY KEY NOT NULL,
Name VARCHAR(50)
)

CREATE TABLE OrderItems(
OrderID INT NOT NULL,
ItemID INT NOT NULL
)

CREATE TABLE Items(
ItemID INT PRIMARY KEY NOT NULL,
Name VARCHAR(50),
ItemTypeID INT
)

CREATE TABLE ItemTypes(
ItemTypeId INT PRIMARY KEY NOT NULL,
Name VARCHAR(50)
)

ALTER TABLE Orders
ADD FOREIGN KEY(CustomerID)
REFERENCES Customers(CustomerID)

ALTER TABLE Customers
ADD FOREIGN KEY(CityID)
REFERENCES Cities(CityID)

ALTER TABLE OrderItems
ADD PRIMARY KEY(OrderID, ItemID)

ALTER TABLE OrderItems
ADD FOREIGN KEY(OrderId)
REFERENCES Orders(OrderID)

ALTER TABLE OrderItems
ADD FOREIGN KEY(ItemID)
REFERENCES Items(ItemID)

ALTER TABLE Items
ADD FOREIGN KEY(ItemTypeID)
REFERENCES ItemTypes(ItemTypeID)